// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	Color       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Permission struct {
	ID          pgtype.UUID
	Name        string
	Resource    string
	Action      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Post struct {
	ID               pgtype.UUID
	Title            string
	Slug             string
	Content          string
	Excerpt          pgtype.Text
	FeaturedImageUrl pgtype.Text
	Status           pgtype.Text
	AuthorID         pgtype.UUID
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PostCategory struct {
	PostID     pgtype.UUID
	CategoryID pgtype.UUID
}

type PostTag struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Username      string
	PasswordHash  string
	FirstName     pgtype.Text
	LastName      pgtype.Text
	AvatarUrl     pgtype.Text
	Bio           pgtype.Text
	IsActive      pgtype.Bool
	EmailVerified pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserProfile struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FirstName  pgtype.Text
	LastName   pgtype.Text
	Bio        pgtype.Text
	AvatarUrl  pgtype.Text
	WebsiteUrl pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type UserRole struct {
	UserID     pgtype.UUID
	RoleID     pgtype.UUID
	AssignedAt pgtype.Timestamptz
	AssignedBy pgtype.UUID
}
