// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            pgtype.UUID
	Email         string
	Username      string
	PasswordHash  string
	FirstName     pgtype.Text
	LastName      pgtype.Text
	AvatarUrl     pgtype.Text
	Bio           pgtype.Text
	IsActive      pgtype.Bool
	EmailVerified pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
