// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID          pgtype.UUID
	Name        string
	Resource    string
	Action      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Username      string
	PasswordHash  string
	FirstName     pgtype.Text
	LastName      pgtype.Text
	AvatarUrl     pgtype.Text
	Bio           pgtype.Text
	IsActive      pgtype.Bool
	EmailVerified pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserRole struct {
	UserID     pgtype.UUID
	RoleID     pgtype.UUID
	AssignedAt pgtype.Timestamptz
	AssignedBy pgtype.UUID
}
