// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignCategoryToPost = `-- name: AssignCategoryToPost :exec
INSERT INTO post_categories (post_id, category_id)
VALUES ($1, $2)
`

type AssignCategoryToPostParams struct {
	PostID     pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) AssignCategoryToPost(ctx context.Context, arg AssignCategoryToPostParams) error {
	_, err := q.db.Exec(ctx, assignCategoryToPost, arg.PostID, arg.CategoryID)
	return err
}

const assignTagToPost = `-- name: AssignTagToPost :exec
INSERT INTO post_tags (post_id, tag_id)
VALUES ($1, $2)
`

type AssignTagToPostParams struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) AssignTagToPost(ctx context.Context, arg AssignTagToPostParams) error {
	_, err := q.db.Exec(ctx, assignTagToPost, arg.PostID, arg.TagID)
	return err
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Title            string
	Slug             string
	Content          string
	Excerpt          pgtype.Text
	FeaturedImageUrl pgtype.Text
	Status           pgtype.Text
	AuthorID         pgtype.UUID
	PublishedAt      pgtype.Timestamptz
}

// -- name: GetPostsByStatus :many
// SELECT * FROM posts WHERE status = $1 ORDER BY updated_at DESC;
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.FeaturedImageUrl,
		arg.Status,
		arg.AuthorID,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.FeaturedImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostBySlug = `-- name: DeletePostBySlug :exec
DELETE FROM posts WHERE slug = $1
`

func (q *Queries) DeletePostBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deletePostBySlug, slug)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.FeaturedImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE slug = $1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.FeaturedImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostsByAuthorID = `-- name: GetPostsByAuthorID :many
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE author_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) GetPostsByAuthorID(ctx context.Context, authorID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByAuthorID, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByCategorySlug = `-- name: GetPostsByCategorySlug :many
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.featured_image_url, p.status, p.author_id, p.published_at, p.created_at, p.updated_at FROM posts p
JOIN post_categories pc ON p.id = pc.post_id
JOIN categories c ON pc.category_id = c.id
WHERE c.slug = $1
ORDER BY p.updated_at DESC
`

func (q *Queries) GetPostsByCategorySlug(ctx context.Context, slug string) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByCategorySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByTagSlug = `-- name: GetPostsByTagSlug :many
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.featured_image_url, p.status, p.author_id, p.published_at, p.created_at, p.updated_at FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
JOIN tags t ON pt.tag_id = t.id
WHERE t.slug = $1
ORDER BY p.updated_at DESC
`

func (q *Queries) GetPostsByTagSlug(ctx context.Context, slug string) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByTagSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedPosts = `-- name: ListArchivedPosts :many
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE status = 'archived' ORDER BY updated_at DESC
`

func (q *Queries) ListArchivedPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listArchivedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftPosts = `-- name: ListDraftPosts :many
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE status = 'draft' ORDER BY updated_at DESC
`

func (q *Queries) ListDraftPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listDraftPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts ORDER BY updated_at DESC
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at FROM posts WHERE status = 'published' ORDER BY updated_at DESC
`

func (q *Queries) ListPublishedPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.FeaturedImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignCategoryFromPost = `-- name: UnassignCategoryFromPost :exec
DELETE FROM post_categories WHERE post_id = $1 AND category_id = $2
`

type UnassignCategoryFromPostParams struct {
	PostID     pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) UnassignCategoryFromPost(ctx context.Context, arg UnassignCategoryFromPostParams) error {
	_, err := q.db.Exec(ctx, unassignCategoryFromPost, arg.PostID, arg.CategoryID)
	return err
}

const unassignTagFromPost = `-- name: UnassignTagFromPost :exec
DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2
`

type UnassignTagFromPostParams struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) UnassignTagFromPost(ctx context.Context, arg UnassignTagFromPostParams) error {
	_, err := q.db.Exec(ctx, unassignTagFromPost, arg.PostID, arg.TagID)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2, slug = $3, content = $4, excerpt = $5, featured_image_url = $6, status = $7, author_id = $8, published_at = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, content, excerpt, featured_image_url, status, author_id, published_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID               pgtype.UUID
	Title            string
	Slug             string
	Content          string
	Excerpt          pgtype.Text
	FeaturedImageUrl pgtype.Text
	Status           pgtype.Text
	AuthorID         pgtype.UUID
	PublishedAt      pgtype.Timestamptz
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.FeaturedImageUrl,
		arg.Status,
		arg.AuthorID,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.FeaturedImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
