// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  username
) VALUES ($1, $2, $3) RETURNING id, email, username
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Username     string
}

type CreateUserRow struct {
	ID       pgtype.UUID
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET
  is_active = false
WHERE id = $1 AND is_active = true
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username FROM users where email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID       pgtype.UUID
	Email    string
	Username string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const getUserByEmailWithPassword = `-- name: GetUserByEmailWithPassword :one
SELECT id, email, username, password_hash FROM users WHERE email = $1 LIMIT 1
`

type GetUserByEmailWithPasswordRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithPassword, email)
	var i GetUserByEmailWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, first_name, last_name, avatar_url, bio, is_active, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIsActive = `-- name: UpdateIsActive :one
UPDATE users
SET
  is_active = $1
WHERE id = $2
RETURNING id, email, username, first_name, last_name, avatar_url, bio, updated_at
`

type UpdateIsActiveParams struct {
	IsActive pgtype.Bool
	ID       pgtype.UUID
}

type UpdateIsActiveRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateIsActive(ctx context.Context, arg UpdateIsActiveParams) (UpdateIsActiveRow, error) {
	row := q.db.QueryRow(ctx, updateIsActive, arg.IsActive, arg.ID)
	var i UpdateIsActiveRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET
  password_hash = $1
WHERE id = $2 AND is_active = true
RETURNING id, email, username, first_name, last_name, avatar_url, bio, updated_at
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

type UpdatePasswordRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.PasswordHash, arg.ID)
	var i UpdatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  username = $1,
  first_name = $2,
  last_name = $3,
  avatar_url = $4,
  bio = $5,
  updated_at = NOW()
WHERE id = $6
  AND is_active = true
RETURNING id, email, username, first_name, last_name, avatar_url, bio, updated_at
`

type UpdateUserParams struct {
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	ID        pgtype.UUID
}

type UpdateUserRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Bio,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.UpdatedAt,
	)
	return i, err
}
