# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - air
    silent: false
  build:
    cmds:
      - go build -o blog-app.exe cmd/server/main.go
  docker:up:
    cmds:
      - docker-compose -f docker/docker-compose.yml --env-file .env  up
  migrate:up:
    cmds:
      - migrate -path ./internal/database/migrations -database "postgres://postgres:postgres@localhost:5433/blogdb?sslmode=disable" up
  migrate:down:
    cmds:
      - migrate -path ./internal/database/migrations -database "postgres://postgres:postgres@localhost:5433/blogdb?sslmode=disable" down
  migrate:create:
    cmds:
      - migrate create -ext sql -dir ./internal/database/migrations {{.name}}
  seed:
    desc: Seed the database with initial roles, permissions, and sample data
    cmds:
      - go run cmd/seed/main.go
  seed:clear:
    desc: Clear existing data and seed the database
    cmds:
      - go run cmd/seed/main.go --clear
  test:
    cmds:
      - go test -v ./...
  sqlc:generate:
    cmds:
      - go tool sqlc generate -f sqlc/sqlc.yaml
  lint:
    cmds:
      - golangci-lint run