package models

import "time"

type PostBase struct {
}

type Post struct {
	ID              *string `json:"id"`
	Title           string  `json:"title"`
	Slug            string  `json:"slug"`
	Content         string  `json:"content"`
	Excerpt         string  `json:"excerpt"`
	FeatureImageURL *string `json:"feature_image_url"`
	Status          string  `json:"status"`
	// optional
	PublishedAt *time.Time `json:"published_at"`
	// we should set it manually using the user data of the current session
	AuthorID string `json:"author_id"`
}

type CreatePostRequest struct {
	Title           string  `json:"title"`
	Content         string  `json:"content"`
	Excerpt         string  `json:"excerpt"`
	FeatureImageURL *string `json:"feature_image_url"`
	Status          string  `json:"status"`
	// autogenerated by us in the request
	// AuthorID    *string    `json:"-"`
	// Slug        *string    `json:"-"`
	// PublishedAt *time.Time `json:"published_at,omitempty"`
}
