package handlers

import (
	"blog-app/internal/config"
	"blog-app/internal/middleware"
	"blog-app/internal/models"
	"blog-app/internal/services"
	"blog-app/internal/utils"
	"errors"
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gosimple/slug"
	"github.com/rs/zerolog/log"
)

type PostHandler struct {
	postService *services.PostService
	appConfig   *config.Config
}

func NewPostHandler(postService *services.PostService, appConfig *config.Config) *PostHandler {
	return &PostHandler{
		postService: postService,
		appConfig:   appConfig,
	}
}

func (h *PostHandler) CreatePost(c *fiber.Ctx) error {
	rawPost := new(models.CreatePostRequest)

	if err := c.BodyParser(rawPost); err != nil {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"invalid body data",
		))
	}

	log.Debug().Msg(fmt.Sprintf("rawPost value: %+v", rawPost))

	if rawPost.Title == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing title",
		))
	}

	if rawPost.Content == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing content",
		))
	}

	if rawPost.FeaturedImageURL == nil {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing feature image url",
		))
	}

	if rawPost.Status == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing status",
		))
	}

	// these fields are "private" and will be only generated by us below
	// if rawPost.AuthorID != nil || rawPost.Slug != nil || rawPost.PublishedAt != nil {
	// 	return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
	// 		utils.CREATE_POST_INVALID_BODY_ERROR,
	// 		"some fields are not available for this operation",
	// 	))
	// }

	currentUser, ok := middleware.GetUserContext(c)
	if !ok {
		return c.Status(fiber.StatusUnauthorized).JSON(utils.NewCustomError(
			utils.USER_NOT_AUTHORIZED_ERROR,
			"user session not found",
		))
	}

	// Always set the author id to the current user!
	authorID := currentUser.ID
	// slug is generated by us
	postSlug := slug.Make(rawPost.Title) + "-" + utils.GenerateRandomString(4)

	post, err := h.postService.CreatePost(models.Post{
		Title:            rawPost.Title,
		Content:          rawPost.Content,
		Excerpt:          rawPost.Excerpt,
		FeaturedImageURL: rawPost.FeaturedImageURL,
		Status:           rawPost.Status,
		// created by us
		Slug:     postSlug,
		AuthorID: authorID,
	})
	if err != nil {
		log.Error().Err(err).Msg("postService.CreatePost: error to create post")
		return c.Status(fiber.StatusInternalServerError).JSON(
			utils.NewCustomError(utils.INTERNAL_SERVER_ERROR, "internal server error"),
		)
	}

	return c.Status(fiber.StatusCreated).JSON(fiber.Map{"success": true, "post": post})
}

func (h *PostHandler) GetPostBySlug(c *fiber.Ctx) error {
	slug := c.Params("slug")

	if slug == "" {
		return c.Status(fiber.StatusBadRequest).JSON(utils.NewCustomError(
			utils.BAD_REQUEST_ERROR,
			"slug param is missing",
		))
	}

	post, err := h.postService.GetPostBySlug(slug)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(utils.NewCustomError(
			utils.INTERNAL_SERVER_ERROR,
			"error to get the post",
		))
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{"success": true, "post": post})
}

func (h *PostHandler) GetPostByID(c *fiber.Ctx) error {
	id := c.Params("id")
	if id == "" {
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(utils.BAD_REQUEST_ERROR, "id param is missing"),
		)
	}

	log.Info().Msg(fmt.Sprintf("id is %s", id))

	post, err := h.postService.GetPostByID(id)
	if err != nil {
		return c.Status(fiber.StatusNotFound).JSON(utils.NewCustomError(
			utils.NOT_FOUND_ERROR,
			fmt.Sprintf("post with id '%s' not found", id),
		))
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{"success": true, "post": post})
}

func (h *PostHandler) GetPostsByAuthorID(c *fiber.Ctx) error {
	authorId := c.Params("authorId")
	if authorId == "" {
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(utils.BAD_REQUEST_ERROR, "authorId param is missing"),
		)
	}
	posts, err := h.postService.GetPostsByAuthorID(authorId)
	if err != nil {
		log.Error().Err(err).Msg(fmt.Sprintf("cannot get posts by author id: %s", authorId))
		return c.Status(fiber.StatusNotFound).JSON(
			utils.NewCustomError(utils.NOT_FOUND_ERROR, fmt.Sprintf("posts not found for author id: %s", authorId)),
		)
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{"success": true, "posts": posts})
}

func (h *PostHandler) UpdatePostByID(c *fiber.Ctx) error {
	id := c.Params("id")
	if id == "" {
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(
				utils.BAD_REQUEST_ERROR,
				"id param is missing",
			),
		)
	}

	if len(c.Body()) == 0 {
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(
				utils.BAD_REQUEST_ERROR,
				"request body is required",
			),
		)
	}

	var updatePostData models.UpdatePostData
	err := c.BodyParser(&updatePostData)
	if err != nil {
		log.Error().Err(err).Msg("updatePostByID handler: error to parse body request")
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(
				utils.BAD_REQUEST_ERROR,
				"cannot process data",
			),
		)
	}

	if updatePostData.IsEmpty() {
		return c.Status(fiber.StatusBadRequest).JSON(
			utils.NewCustomError(
				utils.BAD_REQUEST_ERROR,
				"request body cannot be empty",
			),
		)
	}

	// if updatePostData == (models.UpdatePostData{}) {
	// 	return c.Status(fiber.StatusBadRequest).JSON(
	// 		utils.NewCustomError(
	// 			utils.BAD_REQUEST_ERROR,
	// 			"request body cannot be empty",
	// 		),
	// 	)
	// }

	currentUser, ok := middleware.GetUserContext(c)
	if !ok {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "not authenticated",
		})
	}

	post, err := h.postService.UpdatePostByID(currentUser.ID, id, &updatePostData)
	if err != nil {
		if errors.Is(err, utils.ErrResourceNotFoundInDB) {
			return c.Status(fiber.StatusBadRequest).JSON(
				utils.NewCustomError(
					utils.NOT_FOUND_ERROR,
					fmt.Sprintf("post with id '%s' not found.", id),
				),
			)
		}

		log.Error().Err(err).Msg(fmt.Sprintf("cannot update post with id '%s'", id))
		return c.Status(fiber.StatusInternalServerError).JSON(utils.NewCustomError(
			utils.INTERNAL_SERVER_ERROR,
			"internal server error",
		))
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{"success": true, "post": post})

}

func (h *PostHandler) DeletePostByID(c *fiber.Ctx) error {
	return nil
}
