package handlers

import (
	"blog-app/internal/config"
	"blog-app/internal/middleware"
	"blog-app/internal/models"
	"blog-app/internal/services"
	"blog-app/internal/utils"
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gosimple/slug"
	"github.com/rs/zerolog/log"
)

type PostHandler struct {
	postService *services.PostService
	appConfig   *config.Config
}

func NewPostHandler(postService *services.PostService, appConfig *config.Config) *PostHandler {
	return &PostHandler{
		postService: postService,
		appConfig:   appConfig,
	}
}

func (h *PostHandler) CreatePost(c *fiber.Ctx) error {
	rawPost := new(models.CreatePostRequest)

	if err := c.BodyParser(rawPost); err != nil {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"invalid body data",
		))
	}

	log.Debug().Msg(fmt.Sprintf("rawPost value: %+v", rawPost))

	if rawPost.Title == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing title",
		))
	}

	if rawPost.Content == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing content",
		))
	}

	if rawPost.FeatureImageURL == nil {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing feature image url",
		))
	}

	if rawPost.Status == "" {
		return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
			utils.CREATE_POST_INVALID_BODY_ERROR,
			"missing status",
		))
	}

	// these fields are "private" and will be only generated by us below
	// if rawPost.AuthorID != nil || rawPost.Slug != nil || rawPost.PublishedAt != nil {
	// 	return c.Status(fiber.StatusUnprocessableEntity).JSON(utils.NewCustomError(
	// 		utils.CREATE_POST_INVALID_BODY_ERROR,
	// 		"some fields are not available for this operation",
	// 	))
	// }

	currentUser, ok := middleware.GetUserContext(c)
	if !ok {
		return c.Status(fiber.StatusUnauthorized).JSON(utils.NewCustomError(
			utils.USER_NOT_AUTHORIZED_ERROR,
			"user session not found",
		))
	}

	// Always set the author id to the current user!
	authorID := currentUser.ID
	// slug is generated by us
	postSlug := slug.Make(rawPost.Title) + "-" + utils.GenerateRandomString(4)

	post, err := h.postService.CreatePost(models.Post{
		Title:           rawPost.Title,
		Content:         rawPost.Content,
		Excerpt:         rawPost.Excerpt,
		FeatureImageURL: rawPost.FeatureImageURL,
		Status:          rawPost.Status,
		// created by us
		Slug:     postSlug,
		AuthorID: authorID,
	})
	if err != nil {
		log.Error().Err(err).Msg("postService.CreatePost: error to create post")
		return c.Status(fiber.StatusInternalServerError).JSON(
			utils.NewCustomError(utils.INTERNAL_SERVER_ERROR, "internal server error"),
		)
	}

	return c.Status(fiber.StatusCreated).JSON(fiber.Map{"success": true, "post": post})
}

func (h *PostHandler) GetPostBySlug(c *fiber.Ctx) error {
	return nil
}

func (h *PostHandler) GetPostByID(c *fiber.Ctx) error {
	return nil
}

func (h *PostHandler) GetPostsByAuthorID(c *fiber.Ctx) error {
	return nil
}

func (h *PostHandler) UpdatePostByID(c *fiber.Ctx) error {
	return nil
}

func (h *PostHandler) DeletePostByID(c *fiber.Ctx) error {
	return nil
}
